### ISSUE TITLE
Priceboard containers no longer exist

### ISSUE THREAD

**Issue by nwalke** [ProTip/aws-elk-billing#7]
The images referenced in the compose file are no longer available on Docker hub.

I'm trying out the official elasticsearch/kibana/logstash images and if they work, I'll make a PR.

**Comment by Rammmsankar** [comment]
we are facing an issue as there is no priceboard folder , could you please help us

**Comment by nwalke** [comment]
Forgot I opened this issue.  I don't know what relation ProTip has with PriceBoard, but it'd be nice if they consolidated.  Check out the user PriceBoardIn with the same repo name.  Theirs works.
